exports.dexgen1 = {
    "1":"Bulbasaur, the seed pokemon. A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
    "2":"ivysaur, the seed pokemon. When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", 
    "3":"Venasaur, the seed pokemon. The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
    "4":"Charmander, the lizard pokemon. Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
    "5":"Charmeleon, the flame pokemon. When it swings its burning tail, it elevates the temperature to unbearably high levels.",
    "6":"Charizard, the flame pokemon. Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
    "7":"Squirtle, the tiny turtle pokemon. After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
    "8":"Wartortle, the turtle pokemon. Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.",
    "9":"Blastoise, the shellfish pokemon. A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles.",
    "10":"Caterpie, the worm pokemon. Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
    "11":"Metapod, the cocoon pokemon. This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.",
    "12":"Butterfree, the butterfly pokemon. In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
    "13":"Weedle, the hairy bug pokemon. Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
    "14":"Kakuna, the cocoon pokemon. Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators.",
    "15":"Beedrill, the posoin bee pokemon. Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
    "16":"Pidgey,",
    "17":"Pidgeotto,",
    "18":"Pidgeot,",
    "19":"Rattata,",
    "20":"Raticate,",
    "21":"Spearow,",
    "22":"Fearow,",
    "23":"Ekans,",
    "24":"Arbok,",
    "25":"Pikachu,",
    "26":"Raichu,",
    "27":"Sandshrew,",
    "28":"you caught a sandslash",
    "30":"you caught a nidoran f",
    "30":"you caught a nidorina",
    "31":"you caught a nidoqueen",
    "32":"you caught a nidoran m",
    "33":"you caught a nidorino",
    "34":"you caught a nidoking",
    "35":"you caught a clefairy",
    "36":"you caught a clefable",
    "37":"you caught a vulpix",
    "38":"you caught a ninetails",
    "39":"you caught a jigglypuff",
    "40":"you caught a wigglytuff",
    "41":"you caught a zubat",
    "42":"you caught a golbat",
    "43":"you caught a oddish",
    "44":"you caught a gloom",
    "45":"you caught a vileplume",
    "46":"you caught a paras",
    "47":"you caught a parasect",
    "48":"you caught a venonat",
    "49":"you caught a venomoth",
    "50":"you caught a diglett",
    "51":"you caught a dugtrio",
    "52":"you caught a meowth",
    "53":"you caught a persian",
    "54":"you caught a psyduck",
    "55":"you caught a golduck",
    "56":"you caught a mankey",
    "57":"you caught a primeape",
    "58":"you caught a growlith",
    "59":"you caught a arcenine",
    "60":"you caught a poliwag",
    "61":"you caught a poliwhirl",
    "62":"you caught a poliwrath",
    "63":"you caught a abra",
    "64":"you caught a kadabra",
    "65":"you caught a alakazam",
    "66":"you caught a machop",
    "67":"you caught a machoke",
    "68":"you caught a machamp",
    "69":"you caught a bellsprout",
    "70":"you caught a weepingbell",
    "71":"you caught a victreebell",
    "72":"you caught a tentacool",
    "73":"you caught a tentacreul",
    "74":"you caught a geodude",
    "75":"you caught a graveller",
    "76":"you caught a golem",
    "77":"you caught a ponyta",
    "78":"you caught a rapidash",
    "79":"you caught a slowpoke",
    "80":"you caught a slowbro",
    "81":"you caught a magnemite",
    "82":"you caught a magnetone",
    "83":"you caught a farfetch",
    "84":"you caught a doduo",
    "85":"you caught a dodrio",
    "86":"you caught a seel",
    "87":"you caught a dewong",
    "88":"you caught a grimer",
    "89":"you caught a muk",
    "90":"you caught a shellder",
    "91":"you caught a cloyster",
    "92":"you caught a gastly",
    "93":"you caught a haunter",
    "94":"you caught a gengar",
    "95":"you caught a onix",
    "96":"you caught a drowzee",
    "97":"you caught a hypno",
    "98":"you caught a krabby",
    "99":"you caught a kingler",
    "100":"you caught a voltorb",
    "101":"you caught a electrode",
    "102":"you caught a exeggcute",
    "103":"you caught a exuggutor",
    "104":"you caught a cubone",
    "105":"you caught a marrowak",
    "106":"you caught a hitmonlee",
    "107":"you caught a hitmonchan",
    "108":"you caught a lickytung",
    "109":"you caught a koffing",
    "110":"you caught a weezing",
    "111":"you caught a ryhorn",
    "112":"you caught a ryhdon",
    "113":"you caught a chansey",
    "114":"you caught a tangela",
    "115":"you caught a kangkaskan",
    "116":"you caught a horsea",
    "117":"you caught a seadra",
    "118":"you caught a goldeen",
    "119":"you caught a seaking",
    "120":"you caught a staryu",
    "121":"you caught a starmie",
    "122":"you caught a mr mime",
    "123":"you caught a scyther",
    "124":"you caught a jynx",
    "125":"you caught a electabuzz",
    "126":"you caught a magmar",
    "127":"you caught a pinsir",
    "128":"you caught a tauros",
    "129":"you caught a magikarp",
    "130":"you caught a gyradose",
    "131":"you caught a lapras",
    "132":"you caught a ditto",
    "133":"you caught a eevee",
    "134":"you caught a vaporeon",
    "135":"you caught a jolteon",
    "136":"you caught a flareon",
    "137":"you caught a porygon",
    "138":"you caught a omanyte",
    "139":"you caught a omastar",
    "140":"you caught a kabuto",
    "141":"you caught a kabutops",
    "142":"you caught a aerodacteal",
    "143":"you caught a snorlax",
    "144":"you caught a articuno",
    "145":"you caught a zapdos",
    "146":"you caught a moltres",
    "147":"you caught a dratini",
    "148":"you caught a dragonair",
    "149":"you caught a dragonite",
    "150":"you caught a mewtwo",
    "151":"you caught a mew"
}